// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezyxexkpgixzkaobpqfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6eXhleGtwZ2l4emthb2JwcWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjkxNjEsImV4cCI6MjA2MzY0NTE2MX0.-pnIprkJq8OvqTd7-pFeGXNsudQWfUJyA1cXk9-aHMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);